### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by emrekeles-arch** [levi3001/multiview-mamo#1]
What should be the structure of the folder where the data is located? Should I separate the photos as training and testing and put them in separate folders? Where should the CSV file be?

**Comment by levi3001** [comment]
It is really depend on your design, for Vindr mammo dataset, I just download the dataset and use their csv file and for DDSM dataset, I only split the dataset in the csv file (be sure you split it by patient id)

**Comment by emrekeles-arch** [comment]
there is a data-dir argument, 

> It is really depend on your design, for Vindr mammo dataset, I just download the dataset and use their csv file and for DDSM dataset, I only split the dataset in the csv file (be sure you split it by patient id)

What is the structure of the data_dir folder you use?

Can I train in single view using the VINDr data set? Do I need to make any changes in the Python files? Because you referenced the ddsm.yaml file for single view.
